from .home import *
from .player import *
from .explore import *
from .new_releases import *
from .top_charts import *
from .upload import *
from .playlist import *
from .comment import *
from .genre import *
from .rating import *
from .search import *