"""Added Music Models

Revision ID: 0bee79cff947
Revises: 9f9c40f82254
Create Date: 2023-11-05 18:02:24.255333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bee79cff947'
down_revision = '9f9c40f82254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Genre', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Genre_name'), ['name'], unique=True)

    op.create_table('Flag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('flaged_by', sa.Integer(), nullable=True),
    sa.Column('flaged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['flaged_by'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Flag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Flag_reason'), ['reason'], unique=True)

    op.create_table('Track',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('lyrics', sa.String(), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.Column('flag_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('last_modified_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['Channel.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['User.id'], ),
    sa.ForeignKeyConstraint(['flag_id'], ['Flag.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], ),
    sa.ForeignKeyConstraint(['last_modified_by'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Track', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Track_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Track', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Track_name'))

    op.drop_table('Track')
    with op.batch_alter_table('Flag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Flag_reason'))

    op.drop_table('Flag')
    with op.batch_alter_table('Genre', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Genre_name'))

    op.drop_table('Genre')
    # ### end Alembic commands ###
