"""Updated the TrackSearch Table

Revision ID: 2f5307163bdd
Revises: a06b4f16e1f3
Create Date: 2023-11-21 14:12:34.698405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5307163bdd'
down_revision = 'a06b4f16e1f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TrackSearch_idx')
    op.drop_table('TrackSearch_docsize')
    op.drop_table('TrackSearch_config')
    op.drop_table('TrackSearch_data')
    with op.batch_alter_table('TrackSearch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rowid', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TrackSearch', schema=None) as batch_op:
        batch_op.drop_column('rowid')

    op.create_table('TrackSearch_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TrackSearch_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('TrackSearch_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TrackSearch_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    # ### end Alembic commands ###
