"""Added lyrics to the TrackFTS table

Revision ID: 30831d14917c
Revises: 80e0bc165077
Create Date: 2023-11-21 01:21:40.000091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30831d14917c'
down_revision = '80e0bc165077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TrackFTS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lyrics', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TrackFTS', schema=None) as batch_op:
        batch_op.drop_column('lyrics')

    # ### end Alembic commands ###
