"""Fixed AlbumItem error

Revision ID: 5206558964d9
Revises: 21f282837697
Create Date: 2023-11-22 13:01:09.287913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5206558964d9'
down_revision = '21f282837697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AlbumItem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Album', ['album_id'], ['id'])
        batch_op.drop_column('playlist_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AlbumItem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Album', ['playlist_id'], ['id'])
        batch_op.drop_column('album_id')

    # ### end Alembic commands ###
