"""Fixed incorrect relationship of ablum

Revision ID: 6ad273232ba7
Revises: bfe7acd3c313
Create Date: 2023-11-25 00:54:41.573459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad273232ba7'
down_revision = 'bfe7acd3c313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Album', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Channel', ['last_modified_by'], ['id'])
        batch_op.create_foreign_key(None, 'Channel', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Album', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'User', ['last_modified_by'], ['id'])

    # ### end Alembic commands ###
