"""Added 'is_creator' column to the user table might remove it in the future!

Revision ID: 7a4d0c363512
Revises: f51df18193ce
Create Date: 2023-11-15 18:40:12.005506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a4d0c363512"
down_revision = "f51df18193ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("User", schema=None) as batch_op:
        batch_op.drop_column("is_creator")

    # ### end Alembic commands ###
