"""Added is_active boolean to channel and user tables

Revision ID: 7e0d24a95e44
Revises: bfe7acd3c313
Create Date: 2023-11-28 23:40:31.801322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0d24a95e44'
down_revision = 'bfe7acd3c313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Channel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_Channel_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_User_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_is_active'))
        batch_op.drop_column('is_active')

    with op.batch_alter_table('Channel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Channel_is_active'))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
