"""Added FTS table for Track

Revision ID: 80e0bc165077
Revises: 444eea3edbf2
Create Date: 2023-11-21 01:10:34.617529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e0bc165077'
down_revision = '444eea3edbf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TrackFTS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TrackFTS')
    # ### end Alembic commands ###
