"""Fixed property of the track that makes track.name was set to unique when it was not supposed to be

Revision ID: 8cc104f26ad9
Revises: 0bee79cff947
Create Date: 2023-11-05 19:17:31.342221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cc104f26ad9'
down_revision = '0bee79cff947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Track', schema=None) as batch_op:
        batch_op.drop_index('ix_Track_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Track', schema=None) as batch_op:
        batch_op.create_index('ix_Track_name', ['name'], unique=False)

    # ### end Alembic commands ###
