"""Added Comment table

Revision ID: 90150e31c525
Revises: 8cc104f26ad9
Create Date: 2023-11-10 22:38:24.506256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90150e31c525'
down_revision = '8cc104f26ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('last_modified_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['User.id'], ),
    sa.ForeignKeyConstraint(['last_modified_by'], ['User.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['Track.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Comment')
    # ### end Alembic commands ###
