"""User.nickname is not unique anymore

Revision ID: b770106c550e
Revises: ea270cee6af4
Create Date: 2024-04-14 21:24:33.216663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b770106c550e'
down_revision = 'ea270cee6af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index('ix_User_nickname')
        batch_op.create_index(batch_op.f('ix_User_nickname'), ['nickname'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_nickname'))
        batch_op.create_index('ix_User_nickname', ['nickname'], unique=1)

    # ### end Alembic commands ###
