"""Added moderation columns and Whitelist table

Revision ID: bfe7acd3c313
Revises: 2967f5bd5774
Create Date: 2023-11-24 20:19:15.037631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe7acd3c313'
down_revision = '2967f5bd5774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Channel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blacklisted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('Flag', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_Flag_reason'), ['reason'], unique=True)

    with op.batch_alter_table('Track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Track', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    with op.batch_alter_table('Flag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Flag_reason'))
        batch_op.alter_column('reason',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('Channel', schema=None) as batch_op:
        batch_op.drop_column('blacklisted')

    # ### end Alembic commands ###
