from .album import AlbumAPI
from .comment import CommentAPIV2
from .playlist import PlaylistAPI
from .playlist_item import PlaylistItemAPI
from .rating import RatingAPIV2
from .track import TrackAPIV2
from .recents import RecentsAPI
from .lastest import LatestAPI
from .top import TopAPI
from .genre import GenreAPI
from .search import SearchAPI